-- AlterEnum UserRole
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BRANCH_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SELLER';

-- AlterEnum OrderStatus
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'NEW';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'INVOICED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'IN_COURIER';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PARTIAL_DELIVERED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'COMPLETE';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'HOLD';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'UNMATCH';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'EXCHANGE';

-- AlterEnum LedgerEntryType
ALTER TYPE "LedgerEntryType" ADD VALUE IF NOT EXISTS 'SALE_EARNING';
ALTER TYPE "LedgerEntryType" ADD VALUE IF NOT EXISTS 'WITHDRAWAL';
ALTER TYPE "LedgerEntryType" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_PAYMENT';
ALTER TYPE "LedgerEntryType" ADD VALUE IF NOT EXISTS 'REFUND_DEDUCTION';
ALTER TYPE "LedgerEntryType" ADD VALUE IF NOT EXISTS 'WHOLESALE_PURCHASE';

-- AlterEnum FunnelEventType
ALTER TYPE "FunnelEventType" ADD VALUE IF NOT EXISTS 'INITIATE_CHECKOUT';
ALTER TYPE "FunnelEventType" ADD VALUE IF NOT EXISTS 'PURCHASE';

-- AlterEnum PayoutMethod
ALTER TYPE "PayoutMethod" ADD VALUE IF NOT EXISTS 'ROCKET';

-- AlterEnum PayoutStatus
ALTER TYPE "PayoutStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE "PayoutStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';

-- AlterEnum SubscriptionStatus
ALTER TYPE "SubscriptionStatus" ADD VALUE IF NOT EXISTS 'TRIAL';
ALTER TYPE "SubscriptionStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
